
@server={{$dotenv %CF_SRV_URL}}
@service=storage/


## Get a list of trails
GET {{server}}{{service}}Trails

### Sample Message
POST {{server}}{{service}}Crumbs
Content-Type: application/json

{
    "accelerometerScore": "1.03521728515625",
    "accelerometerX": "0.0090789794921875",
    "accelerometerY": "-0.02618408203125",
    "accelerometerZ": "-0.9999542236328125",
    "addressCity": "Heidelberg",
    "addressPostalCode": "69115",
    "addressState": "Baden-Württemberg",
    "addressStreet": "Vangerowstraße",
    "crumbTime": "2022-05-31T13:18:37.000Z",
    "deviceId": "76F19B03-E2ED-4193-B774-C1D33C393C05",
    "emergencyContacted": false,
    "fallDetected": false,
    "locationLat": 49.409333110333414,
    "locationLong": 8.673441922678654,
    "personId": "Martin Stenzig",
    "speedMPH": "0.0",
    "ID": "37c724e4-0aa2-48c8-8ca5-f3ecf9b28c83",
    "Device_ID": "76F19B03-E2ED-4193-B774-C1D33C393C05",
    "createdAt": "2022-05-31T13:09:51.778Z",
    "createdBy": "privileged",
    "modifiedAt": "2022-05-31T13:09:51.778Z",
    "modifiedBy": "privileged"
}

### Populate the database with some data
POST {{server}}{{service}}Crumbs
Content-Type: application/json

{
       "accelerometerScore": 2.33062744140625,
       "accelerometerX": 0.1887359619140625,
       "accelerometerY": -0.3112030029296875,
       "accelerometerZ": -1.8306884765625,
       "addressCity": "Seattle",
       "addressPostalCode": "98118",
       "addressState": "WA",
       "addressStreet": "39th Ave S",
       "crumbTime": "{{$datetime iso8601}}",
       "deviceId": "76F19B03-E2ED-4193-B774-C1D33C393C05",
       "fallDetected": false,
       "locationLat": 47.569579719215746,
       "locationLong": -122.28437000206462,
       "personId": "Martin",
       "speedMPH": 0.02
}

### Populate the database with some data
POST {{server}}{{service}}Crumbs
Content-Type: application/json

{
       "accelerometerScore": 2.33062744140625,
       "accelerometerX": 0.1887359619140625,
       "accelerometerY": -0.3112030029296875,
       "accelerometerZ": -1.8306884765625,
       "addressCity": "Seattle",
       "addressPostalCode": "98118",
       "addressState": "WA",
       "addressStreet": "39th Ave S",
       "crumbTime": "{{$datetime iso8601}}",
       "deviceId": "76F19B03-E2ED-4193-B774-C1D33C393C05",
       "fallDetected": true,
       "locationLat": 47.669579719215746,
       "locationLong": -122.38437000206462,
       "personId": "Martin",
       "speedMPH": 2.02
}

### Read all Crumbs
GET {{server}}{{service}}Crumbs?$top=5

### Read all devices
GET {{server}}{{service}}Devices

### Delete Martin "s phone
PATCH {{server}}{{service}}Devices( "76F19B03-E2ED-4193-B774-C1D33C393C05 ")
Content-Type: application/json

{
"notification": null
}