
@server=http://localhost:4004/
@service=storage/


### Populate the database with some data
POST {{server}}{{service}}Crumbs
Content-Type: application/json

{
       "accelerometerScore": 2.33062744140625,
       "accelerometerX": 0.1887359619140625,
       "accelerometerY": -0.3112030029296875,
       "accelerometerZ": -1.8306884765625,
       "addressCity": "Seattle",
       "addressPostalCode": "98118",
       "addressState": "WA",
       "addressStreet": "39th Ave S",
       "crumbTime": "2022-04-21T14:41:54Z",
       "deviceId": "76F19B03-E2ED-4193-B774-C1D33C393C05",
       "fallDetected": false,
       "locationLat": 47.569579719215746,
       "locationLong": -122.28437000206462,
       "personId": "Martin",
       "speedMPH": 0.02
}

### Populate the database with some data
POST {{server}}{{service}}Crumbs
Content-Type: application/json

{
       "accelerometerScore": 2.33062744140625,
       "accelerometerX": 0.1887359619140625,
       "accelerometerY": -0.3112030029296875,
       "accelerometerZ": -1.8306884765625,
       "addressCity": "Seattle",
       "addressPostalCode": "98118",
       "addressState": "WA",
       "addressStreet": "39th Ave S",
       "crumbTime": "2022-04-21T14:41:54Z",
       "deviceId": "76F19B03-E2ED-4193-B774-C1D33C393C05",
       "fallDetected": false,
       "locationLat": 47.669579719215746,
       "locationLong": -122.38437000206462,
       "personId": "Martin",
       "speedMPH": 2.02
}


### Read all Crumbs
GET {{server}}{{service}}Crumbs
